move script to bash

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -1,64 +1,52 @@
-#!/usr/bin/env python3
+#!/bin/bash
 
-import os
-import argparse
+set -e
 
-parser = argparse.ArgumentParser()
-parser.add_argument("action", nargs="?", choices=["sync", "unlink", "copy"],
-                    help="Choose what action to execute")
-parser.add_argument('--skip', "-s", nargs="*", default=False,
-                    help='If set, software choosed while not be affected by the action.')
+dotfiles_config="~/.dotfiles/config"
+arg_list=("sync" "link" "install")
 
-args = parser.parse_args()
-print(args)
+if [ -d "$dotfiles_config" ]; then
+    echo "The folder $dotfiles_config does not exist."
+    exit 1
+fi
 
-supported_softwares = (
-    "alacritty",
-    "firefox",
-    "git",
-    "nvim",
-    "tmux",
-    "zsh"
-)
+cd ~/.dotfiles
 
-class CLI:
-    def __init__(self, supported_softwares, arg_list):
-        self.args = arg_list
-        self.software_list = list(supported_softwares)
+if [ $# -gt 1 ]; then
+    echo "There is too much arguments."
+    exit 1
+elif [ $# -lt 1 ]; then
+    echo "There is not enough arguments."
+    exit 1
+fi
 
-    def init(self):
-        if not self.args.action:
-            print("You need to choose an action")
-            exit(1)
-        if self.args.skip:
-            for skip in self.args.skip:
-                if skip not in self.software_list:
-                    print(f"The software '{skip}' is not supported to skip.")
-                    exit(1)
-                else:
-                    self.software_list.remove(skip)
+# Install packages needed for config
+install () {
+    echo "install"
+}
 
-    def exec(self, action):
-        if action == "pull":
-            self.pull()
-        elif action == "sync":
-            self.sync()
-        elif action == "unlink":
-            self.unlink()
-        else:
-            print("This action does not exist")
-            exit(1)
+# Synchronize config with remote on git
+sync () {
+    git pull
+}
 
-    def pull(self):
-        print("pull")
+# Link local config to dotfiles folder
+link () {
+    echo "link"
+}
 
-    def sync(self):
-        print("sync")
-
-    def unlink(self):
-        print("unlink")
-
-
-dotfiles = CLI(supported_softwares, args)
-dotfiles.init()
-dotfiles.exec(args.action)
+if [[ ! " ${arg_list[*]} " == *" $1 "* ]]; then
+    echo "The argument '$1' does not exist."
+    exit 1
+else
+    if [ "$1" == "install" ]; then
+        install
+    elif [ "$1" == "sync" ]; then
+        sync
+    elif [ "$1" == "link" ]; then
+        link
+    else
+        echo "Error with argument '$1'."
+        exit 1
+    fi
+fi
